[Fix] og:descriptionを設定
tsukuba-shinkan/shinkan-web pull request #121
Opened 2020-04-07 16:45 UTC by mkobayashime

## 修正するIssue

#116 

## 変更点

- 個別ページの`description`を`activityIntroduce`の先頭200字に設定
- aboutページの`description`を当該ページの一段落目に設定(ハードコーディング)

なお、これにより`description`/`og:description`/`twitter:description`の3つが全て変更されます。

2020-04-07 23:46 UTC, nandenjin requested changes

2020-04-07 23:46 UTC, nandenjin commented on src/templates/PostTemplate.js
> +        description={org.activityIntroduce.substr(0, 200)}
`String.prototype.substr()` は非推奨なようなので、代替に `slice()` or `substring()` が使えませんかね？🤔

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/substr

2020-04-08 00:31 UTC, nandenjin commented on src/templates/PostTemplate.js
> +        description={org.activityIntroduce.substr(0, 200)}
言ってから別作業してて気づきましたが`index.js`では`substr`使っちゃってますね……すみません……

2020-04-08 00:42 UTC, mkobayashime commented on src/templates/PostTemplate.js
> +        description={org.activityIntroduce.substr(0, 200)}
`index.js`と処理揃える意図で`substr`使ったんですがどうしましょう?

2020-04-08 00:55 UTC, nandenjin commented on src/templates/PostTemplate.js
> +        description={org.activityIntroduce.substr(0, 200)}
ですよね〜`index.js`書いた時は気づいてなかったんだと思うのですが、[`PostTemplate.js`書く時に一度調べて`slice`に書き直した](https://github.com/tsukuba-shinkan/shinkan-web/blob/dev/src/templates/PostTemplate.js#L221)ので、お手数でなければ`index.js`の方を修正して`slice`か`substring`に揃えていただくことはできますか……すみません……

2020-04-08 02:48 UTC, mkobayashime commented on src/templates/PostTemplate.js
> +        description={org.activityIntroduce.substr(0, 200)}
@nandenjin 承知しました
このPRに混ざるの気持ち悪い気もしますが、別に切りましょうか?

2020-04-08 02:51 UTC, nandenjin commented on src/templates/PostTemplate.js
> +        description={org.activityIntroduce.substr(0, 200)}
@mkobayashime これしきのために2つもPRたてるのもアレなので、ロジック統一目的という建前で同じPRでも良いかなと思いますが、別に上げていただいても構いません！

別立てする際もこのレビューを参照していただければIssueは作らなくて大丈夫だと思います

2020-04-08 02:52 UTC, mkobayashime commented on src/templates/PostTemplate.js
> +        description={org.activityIntroduce.substr(0, 200)}
ではこのPRでまとめて直しちゃいますね

2020-04-08 03:07 UTC, mkobayashime commented
@nandenjin `slice`に直しましたのでお願いします。全ファイル検索で`substr`が残ってないことは確認しました。

2020-04-08 03:09 UTC, nandenjin approved these changes
@mkobayashime ありがとうございます！お手数おかけしました🙏

2020-04-08 03:42 UTC, AsagaKosho approved these changes

2020-04-08 03:42 UTC, merged