[WIP] Introduce gatsby-images etc.
tsukuba-shinkan/shinkan-web pull request #64
Opened 2020-04-01 10:59 UTC by yuki-js

## 修正するIssue

#18

## 変更点

* プラグイン追加
* ノード追加している
* Imgコンポーネント入れる

2020-04-02 02:50 UTC, yuki-js commented
CSSのレイアウトを消したりしてます。

2020-04-02 07:56 UTC, AsagaKosho requested changes
@yuki-js 
いくつかlintのwarningが出ていますので対応お願いいたします

@nandenjin 
その他の点について確認お願いします

2020-04-02 11:57 UTC, yuki-js commented
Fixed

2020-04-02 12:10 UTC, nandenjin requested changes

2020-04-02 12:10 UTC, nandenjin commented on src/components/BigImg.js
> +  const imageNode = allImages.allImageSharp.nodes.find(e => e.parent.url == url)
linterからwarningが出ています。すみませんこれは本来errorにすべきですね……修正検討します……

2020-04-02 12:10 UTC, nandenjin commented on src/components/Img.js
> +  const imageNode = allImages.allImageSharp.nodes.find(e => e.parent.url == url)
こちらもlinterのwarningを解決してください:pray:

2020-04-02 12:10 UTC, nandenjin commented on src/components/OtherImg.js
> +  const imageNode = allImages.allImageSharp.nodes.find(e => e.parent.url == url)
こちらもlinterの解決をお願いします:pray:

2020-04-02 12:10 UTC, nandenjin commented on src/components/SmallPoster.js
> +  const imageNode = allImages.allImageSharp.nodes.find(e => e.parent.url == url)
こちらもlinterの解決をお願いします:pray:

2020-04-02 12:10 UTC, nandenjin commented on package.json
> +    "gatsby-plugin-manifest": "^2.3.3",
`gatsby-plugin-manifest`のバージョンが上がっているようですがこれはこの作業に関係ありました？

2020-04-02 12:10 UTC, nandenjin commented on src/templates/PostTemplate.js
> +import OtherImg from "../components/OtherImg"
`BigImg` / `OtherImg`について、抽象的な命名にかなり具体的な実装が入ってしまっているので、「このページ特有のソースコードの分割」と割り切って、それがわかるような具体的な名前（`PostTemplatePosterImg`など）に変更するのはどうでしょうか？:thinking:（他ファイルの名前も同様）

2020-04-02 12:14 UTC, AsagaKosho approved these changes

2020-04-02 12:15 UTC, nandenjin requested changes
1回目のレビューと同様です！よろしくお願いします

2020-04-03 03:17 UTC, asagatto777 commented
@yuki-js
@nandenjin さんのレビュー、対応よろしくお願いします

2020-04-03 06:34 UTC, yuki-js commented on package.json
> +    "gatsby-plugin-manifest": "^2.3.3",
内部のモジュールのバージョン不一致でアップデートしてくださいと表示されたのでアップデートしました

2020-04-03 06:44 UTC, yuki-js commented on src/templates/PostTemplate.js
> +import OtherImg from "../components/OtherImg"
`PostTemplatePosterImg`のように、ページ名と役割名の組から命名するなら、名前空間で分けた方がいいような。だけど今のディレクトリ構造的には`PostTemplatePosterImg`とした方がいいのか…

命名規則を決めた方がいいかもしれない。
とりあえずあとで直しておきます。

2020-04-03 09:01 UTC, AsagaKosho requested changes
Conflictの修正お願いします

2020-04-03 09:13 UTC, yuki-js commented on src/templates/PostTemplate.js
> +import OtherImg from "../components/OtherImg"
`src/index.js`の`SmallPoster`は提案いただいた規則に従うと`IndexSmallPoster`になりますが、違和感があります。
大きさのpropsを持つことができれば良いですが、Gatsbyではクエリの動的生成はできないし、一つのコンポーネントファイルはGatsbyのクエリを一つしか持てないので、現状が妥協案だと思います…

2020-04-03 13:04 UTC, nandenjin commented on src/templates/PostTemplate.js
> +import OtherImg from "../components/OtherImg"
少し長くなりそうなのでPR自体のコメントに飛ばします！🙇‍♂️

2020-04-03 13:11 UTC, nandenjin commented
こちら https://github.com/tsukuba-shinkan/shinkan-web/pull/64#discussion_r402262875 のコンポーネントの命名について、名前から具体的な仕様が明らかでなく、またこのままサイト内での`Big`/`Small`の基準をこのコンポーネントの実装のみに委ねることはできないので、何かしらの対策が必要と思っています。

以下どちらかが取りうる解決策かなぁと思うのですが、他の案があればぜひお寄せください🙇‍♂️

* **なんらかの形で命名により具体的な要素を入れる**
  * Ex: サイズについて名前に含める
  * Ex: ページ固有のコンポーネントとし、ページ名を含める（or ファイルを分けないで実装する）
* **`Big`/`Small`などの単語について、具体的な基準を明文化し、このコンポーネント以外でも再利用できるようにする。**
  * スタイルシートのブレークポイントが似た概念だと思います。これを値として流用しても良いかもです🤔
  
もっといい案があればどんどんご意見いただきたいです。どうぞよろしくお願いします🙏

---

* （上記コメントで稲田の提案した命名法、確かどこかで読んだものを参考にして使っているのですが、ソースが見つかりませんでした……すみません……）
* （直接関わりはないですが、こういう時って`Big`ではなく`Large`（-`Medium`-`Small`）っていう命名しませんかね？根拠となるものがあればスタイルシートでのブレークポイントの命名くらいしかないので、これもどなたか意見あれば欲しいです）

2020-04-03 13:12 UTC, nandenjin reviewed
https://github.com/tsukuba-shinkan/shinkan-web/pull/64#issuecomment-608424856 🙏

2020-04-03 18:55 UTC, yuki-js commented
前者の方法を採用しFluid300とかFixed500と、クエリに基づいて命名するといいかと思いますが、どうでしょうか？賛同いただければ採用します。

2020-04-04 03:34 UTC, nandenjin commented
@yuki-js ありがとうございます……！よろしくお願いします:pray:

2020-04-04 16:36 UTC, AsagaKosho reviewed
ありがとうございます！ 👍

2020-04-04 16:36 UTC, AsagaKosho approved these changes

2020-04-05 01:11 UTC, nandenjin approved these changes
![LGTM](https://i.lgtm.fun/pw4.gif)

2020-04-05 01:13 UTC, nandenjin commented
@yuki-js あと申し訳ないんですが今後のcommitではContribution Guideを再度確認の上、メッセージへのプレフィックスの付与を徹底願います……:pray:

2020-04-05 01:13 UTC, merged