floatをflexboxに置き換え
tsukuba-shinkan/shinkan-web pull request #69
Opened 2020-04-01 15:47 UTC by mkobayashime

## 修正するIssue

#56 

## 変更点

`float`で書かれているスタイルを`flexbox`に置き換える…はずだったんですが、僕が #57 (マージ済み)で整合性を確保するために一部`float`を`flexbox`に置き換えたこともあって既に`float`を使った実装は1つもなくなっていたので、`layout.scss`から`float`関連の記述を削除したのみです。

2020-04-01 22:40 UTC, AsagaKosho approved these changes
👍 
@nandenjin Reviewお願いします

2020-04-01 23:41 UTC, AsagaKosho requested changes
PostTemplate.jsにfloat適用箇所残ってました、お手数をおかけしますが確認お願いします。

2020-04-02 00:50 UTC, mkobayashime commented
あっ申し訳ない確認します

2020-04-02 06:50 UTC, mkobayashime commented
@asagatto777 `PostTemplate.js`の当該箇所修正しましたのでご確認ください。

2020-04-02 07:54 UTC, AsagaKosho approved these changes
ありがとうございます！
おそらくこれで #71 も解決したと思います。
@nandenjin Reviewお願いします

2020-04-02 12:31 UTC, nandenjin approved these changes
遅くなりました！

![LGTM](https://i.lgtm.fun/po8.gif)

2020-04-02 12:31 UTC, merged